### ISSUE TITLE
Contact Trace returning 500 status

### ISSUE THREAD

**Issue by jpbottinelli** [quarentime/quarentime-back-end#45]
This is a flaky test, so it's not reproduced every time:
Create a user. Add Personal Information, create Survey like this -> 
```
{
        "has_recent_travel_last14_days": false,
        "has_recent_travel_before_symptoms": false,
        "has_close_contact": false,
        "has_symptoms": false,
        "has_recovered": false,
        "is_tested_positive": true,
        "symptoms": []
    }
```

Then call /User/Contacts/Trace:
the response is:
```
{
    "request_id": "26b27c9c-2a4b-4150-8481-8bf6b79cb671",
    "error_code": "internal_server_error"
}
```
And the logs show:
`textPayload: "2020-04-10 07:27:26.3060|ERROR|User.Api.Filters.ExceptionFilter|Object reference not set to an instance of an object."
`

![image](https://user-images.githubusercontent.com/259956/78972468-321b3f00-7ae4-11ea-83b3-005ffd29fee2.png)

when this happens, also the /User/PersonalInformation request fails and I have to do a new POST only to PersonalInformation, with the exact same data (not generating a new token or anything). That makes it work, but looks like a DB or some data issue

**Comment by edmarsj** [comment]
I was able to reproduce this scenario by creating a user and creating the survey without adding data to the personal information endpoint. 
I'll change this to return a 404 in case you call the contact trace without personal information.

**Comment by jpbottinelli** [comment]
fixed

**Comment by jpbottinelli** [comment]
@edmarsj I found the original problem. Sometimes the PersonalInformation POST request returns 201, but the user is not registered and that's why the PersonalInformation GET and the Trace GET failed when I tested manually. 
I thought that I was rushing too much between requests, but no. I have to regenerate the User
