### ISSUE TITLE
All POST return 200 status code instead of 201

### ISSUE THREAD

**Issue by jpbottinelli** [quarentime/quarentime-back-end#6]
How to reproduce:
POST https://quarentime-user-api-rcgccs4vga-ew.a.run.app/User/PersonalInformation
Body: ```
{
	"email": "test_jpb@quarentime.org",
	"name": "Test User 001",
	"phone_number": "+5491133108174",
	"age": 34
}
```

Other
POST https://quarentime-user-api-rcgccs4vga-ew.a.run.app/User/Survey
Body: ```
{
        "has_recent_travel_last14_days": false,
        "has_recent_travel_before_symptoms": false,
        "has_close_contact": false,
        "has_symptoms": false,
        "has_recovered": false,
        "is_tested_positive": true,
        "symptoms": [1,2
        	]
    }
```

Response status is 200 instead of 201.

Marking it as blocker as it could break integrations with other systems. Please assess and change accordingly

**Comment by edmarsj** [comment]
Changed post endpoints to return 201 instead of 200.
Ps. note that the /User/ConfirmVerificationCode endpoint won't change, as that endpoint does not create any resource.
